language: objective-c
branches:
  only:
  - master
xcode_workspace: Emome.xcworkspace
xcode_scheme: EmomeTests
osx_image: xcode7
xcode_sdk: iphonesimulator9.0
before_install:
- brew update
- brew uninstall xctool && brew install --HEAD xctool
before_script:
- ./script/add-key.sh
script:
- xctool clean build test -workspace Emome.xcworkspace -scheme EmomeTests -sdk iphonesimulator9.0 dONLY_ACTIVE_ARCH=NO
after_success:
- ./script/dist-fabric-io.sh
after_script:
- ./script/remove-key.sh
env:
  global:
  - WORKSPACE="Emome.xcworkspace"
  - SCHEME="EmomeTests"
  - APP_NAME="Emome"
  - ARCHIVE_PATH=`pwd`/archive
  - PROJECT_BUILD_DIR=${ARCHIVE_PATH}/${APP_NAME}.xcarchive/Products/Applications

