language: objective-c
branches:
  only:
  - master
xcode_workspace: Emome.xcworkspace
xcode_scheme: EmomeTests
osx_image: xcode7
xcode_sdk: iphonesimulator9.0
before_install:
- brew update
- brew uninstall xctool && brew install --HEAD xctool
script:
- xctool clean build test -workspace Emome.xcworkspace -scheme EmomeTests -sdk
  iphonesimulator9.0 dONLY_ACTIVE_ARCH=NO
after_success:
- /bin/bash ./archive.sh
- ./Pods/Crashlytics/Crashlytics.framework/submit $FABRIC_API_KEY $FABRIC_BUILD_SECRET -groupAliases ﻿"early-birds" -ipaPath "./archive/Emome.ipa"
