language: objective-c
branches:
  only:
  - master
xcode_workspace: Emome.xcworkspace
xcode_scheme: EmomeTests
osx_image: xcode7.1
xcode_sdk: iphonesimulator9.1
before_install:
- brew update || brew update
- brew uninstall xctool && brew install --HEAD xctool

install:
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet

before_script:
- ./script/add-key.sh
script:
- xcodebuild -workspace ${WORKSPACE} -scheme ${SCHEME} -sdk iphonesimulator9.1 -destination platform='iOS Simulator',OS=9.1,name='iPhone 6s' dONLY_ACTIVE_ARCH=NO clean build | xcpretty -c || true
- xcodebuild -workspace ${WORKSPACE} -scheme ${SCHEME} -sdk iphonesimulator9.1 -destination platform='iOS Simulator',OS=9.1,name='iPhone 6s' dONLY_ACTIVE_ARCH=NO test | xcpretty -c
after_success:
- ./script/dist-fabric-io.sh
after_script:
- ./script/remove-key.sh
env:
  global:
  - WORKSPACE="Emome.xcworkspace"
  - SCHEME="Emome"
  - APP_NAME="Emome"
  - ARCHIVE_PATH=`pwd`/archive
  - PROJECT_BUILD_DIR=${ARCHIVE_PATH}/${APP_NAME}.xcarchive/Products/Applications

