language: objective-c
 
branches:
 only:
 - master
    
xcode_workspace: Emome.xcworkspace
xcode_scheme: EmomeTests,EmomeUITests 
osx_image: xcode7
xcode_sdk: iphonesimulator9.0

script:
- xctool clean build test -workspace Emome.xcworkspace -scheme EmomeTests -sdk iphonesimulator9.0 ONLY_ACTIVE_ARCH=NO
